// AUTO-GENERATED by vscroll plugin installer. Do not edit by hand.
import { adaptLnreaderPlugin } from '../adapter';
import { VScrollPlugin } from '../types';

import _p0_royalroad from './royalroad';

export const installedPlugins: VScrollPlugin[] = [
  adaptLnreaderPlugin(_p0_royalroad as any),
];
