import * as vscode from 'vscode';
import * as fs from 'fs/promises';
import * as path from 'path';
import { AvailablePlugin, fetchPluginSource } from './registry';

const INSTALLED_DIR = ['src', 'plugins', 'installed'];
const INDEX_FILE = 'index.ts';

export interface InstallContext {
  extensionPath: string;
}

export function isDevModeInstall(extensionPath: string): boolean {
  // Heuristic: dev mode means src/plugins exists and is writable. In a packaged
  // extension only the bundled out/ folder is present.
  const pluginsDir = path.join(extensionPath, 'src', 'plugins');
  try {
    require('fs').accessSync(pluginsDir, require('fs').constants.W_OK);
    return true;
  } catch {
    return false;
  }
}

export async function installPlugin(
  ctx: InstallContext,
  available: AvailablePlugin,
): Promise<{ filePath: string; needsReload: true }> {
  if (!isDevModeInstall(ctx.extensionPath)) {
    throw new Error(
      'Plugin install requires the vscroll source workspace to be open (dev mode). ' +
        'Production install is not yet implemented.',
    );
  }

  const installedDir = path.join(ctx.extensionPath, ...INSTALLED_DIR);
  await fs.mkdir(installedDir, { recursive: true });

  const source = await fetchPluginSource(available);
  const rewritten = rewriteImports(source);

  const filePath = path.join(installedDir, available.filename);
  await fs.writeFile(filePath, rewritten, 'utf8');

  await regenerateInstalledIndex(installedDir);

  return { filePath, needsReload: true };
}

export async function uninstallPlugin(
  ctx: InstallContext,
  pluginId: string,
): Promise<void> {
  if (!isDevModeInstall(ctx.extensionPath)) {
    throw new Error('Uninstall requires dev mode.');
  }
  const installedDir = path.join(ctx.extensionPath, ...INSTALLED_DIR);
  const filePath = path.join(installedDir, `${pluginId}.ts`);
  try {
    await fs.unlink(filePath);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
  }
  await regenerateInstalledIndex(installedDir);
}

export async function listInstalledFiles(extensionPath: string): Promise<string[]> {
  const dir = path.join(extensionPath, ...INSTALLED_DIR);
  try {
    const entries = await fs.readdir(dir);
    return entries.filter((f) => f.endsWith('.ts') && f !== INDEX_FILE);
  } catch {
    return [];
  }
}

function rewriteImports(source: string): string {
  // Map all `@libs/*` and `@/*` imports to our shim file. The shim file
  // re-exports fetchApi/storage from runtime, plus NovelStatus/FilterTypes/etc.
  return source
    .replace(/from\s+['"]@libs\/[^'"]+['"]/g, "from '../lnreader-shims'")
    .replace(/from\s+['"]@\/[^'"]+['"]/g, "from '../lnreader-shims'");
}

async function regenerateInstalledIndex(installedDir: string): Promise<void> {
  const files = (await fs.readdir(installedDir))
    .filter((f) => f.endsWith('.ts') && f !== INDEX_FILE)
    .sort();

  const lines: string[] = [
    '// AUTO-GENERATED by vscroll plugin installer. Do not edit by hand.',
    "import { adaptLnreaderPlugin } from '../adapter';",
    "import { VScrollPlugin } from '../types';",
    '',
  ];

  files.forEach((f, i) => {
    const id = f.replace(/\.ts$/, '');
    const safe = id.replace(/[^a-zA-Z0-9_]/g, '_');
    lines.push(`import _p${i}_${safe} from './${id}';`);
  });
  lines.push('');
  lines.push('export const installedPlugins: VScrollPlugin[] = [');
  files.forEach((f, i) => {
    const id = f.replace(/\.ts$/, '');
    const safe = id.replace(/[^a-zA-Z0-9_]/g, '_');
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    lines.push(`  adaptLnreaderPlugin(_p${i}_${safe} as any),`);
  });
  lines.push('];');
  lines.push('');

  await fs.writeFile(path.join(installedDir, INDEX_FILE), lines.join('\n'), 'utf8');
}
